# Introduction

# Literature Review

# Methodology

# Data

```{r}
#| include: false
#| warning: false
#| message: false

library(forecast)
library(ggplot2)
library(gridExtra)
library(tidyverse)
library(corrplot)

price <- read_csv(here::here("data/cleaned_data/price_data.csv"))
climate <- read_csv(here::here("data/cleaned_data/climate_data.csv"))
cocoa <-read_csv(here::here("data/cleaned_data/cocoa_data.csv"))
```

```{r}
# price and temperature since 2000
price_2000 <- price %>% filter(Date >= as.Date("2000-01-01"))
climate_2000 <- climate %>% filter(DATE >= as.Date("2000-01-01"))
ggplot(price_2000, aes(x = Date, y = monthly_avg_price)) + 
  geom_line(color = "black", size = 0.6) +  
  scale_x_date(date_breaks = "1 year", date_labels = "%Y") + 
  labs(x = "Year", y = "Monthly Average Price (USD/tonne)", 
       title = "Monthly Average Cocoa Price (2000-Present)") + 
  theme_minimal()

ggplot(climate_2000, aes(x = as.Date(paste0(YearMonth, "-01")), y = monthly_avg_temp)) +
  geom_line() +
  scale_x_date(date_breaks = "1 year", date_labels = "%Y") +
  labs(x = "Year", y = "Monthly Average Temperature", 
       title = "Monthly Average Temperature (2000-Present)") +
  theme_minimal()


# price and temperature since 2023
price_2023 <- price %>% filter(Date >= as.Date("2023-01-01"))
climate_2023 <- climate %>% filter(DATE >= as.Date("2023-01-01"))
ggplot(price_2023, aes(x = Date, y = monthly_avg_price)) + 
  geom_line(color = "#1f40b4", size = 1) +  
  scale_x_date(date_breaks = "1 year", date_labels = "%Y") + 
  labs(x = "Year", y = "Monthly Average Price (USD/tonne)", 
       title = "Monthly Average Cocoa Price (2023-Present)") + 
  theme_minimal()

ggplot(climate_2023, aes(x = as.Date(paste0(YearMonth, "-01")), y = monthly_avg_temp)) +
  geom_line() +
  scale_x_date(date_breaks = "1 year", date_labels = "%Y") +
  labs(x = "Year", y = "Monthly Average Temperature", 
       title = "Monthly Average Temperature (2023-Present)") +
  theme_minimal()

```
```{r}

```





# Forecasting and Results

# Discussion and Conclusion

# Appendix

# References